---
- name: Capture the list of servers
  ansible.builtin.set_stats:
    data:
      my_server_list: "{{ ansible_play_hosts_all }}"

- name: Capture the list of groups
  ansible.builtin.set_stats:
    data:
      my_groups: "{{ group_names }}"
