---
- name: Ensure the vpc is gone
  register: my_vpc
  google.cloud.gcp_compute_network:
    name: "{{ network_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    state: "{{ state }}"

- name: print shit out
  ansible.builtin.debug:
    var: my_vpc
