---
- name: Ensure we have a disk for our vm
  register: disk
  google.cloud.gcp_compute_disk:
    name: "{{ disk_name }}"
    size_gb: "{{ disk_size }}"
    source_image: "{{ disk_image }}"
    zone: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: "{{ state }}"

- name: Ensure we have an address for our vm
  register: address
  google.cloud.gcp_compute_address:
    name: "{{ address_name }}"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: "{{ state }}"

- name: create a instance
  google.cloud.gcp_compute_instance:
    name: test_object
    machine_type: n1-standard-1
    disks:
    - auto_delete: 'true'
      boot: 'true'
      source: "{{ disk_name }}"
    - auto_delete: 'true'
      interface: NVME
      type: SCRATCH
      initialize_params:
        disk_type: local-ssd
    metadata:
      startup-script-url: gs:://graphite-playground/bootstrap.sh
      cost-center: '12345'
    labels:
      environment: production
    network_interfaces:
    - network: "{{ net_instance }}"
      access_configs:
      - name: External NAT
        nat_ip: "{{ address_name }}"
        type: ONE_TO_ONE_NAT
    zone: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    state: "{{ state }}"
