---
- name: Ensure we have a disk for our vm
  register: disk
  google.cloud.gcp_compute_disk:
    name: "{{ disk_name }}"
    size_gb: "{{ disk_size }}"
    source_image: "{{ disk_image }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    state: "{{ state }}"

- name: Ensure we have a network
  register: network
  google.cloud.gcp_compute_network:
    name: "{{ network_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    state: "{{ state }}"

- name: Ensure we have an address for our vm
  register: address
  google.cloud.gcp_compute_address:
    name: "{{ address_name }}"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    state: "{{ state }}"

- name: Ensure we have an instance
  google.cloud.gcp_compute_instance:
    name: "{{ server_name }}"
    machine_type: "{{ machine_type }}"
    disks:
    - auto_delete: 'true'
      boot: 'true'
      source: '{{ disk }}'
    - auto_delete: 'true'
      interface: NVME
      type: SCRATCH
      initialize_params:
        disk_type: local-ssd
    metadata:
      startup-script-url: gs:://graphite-playground/bootstrap.sh
      cost-center: "{{ cost_center }}"
    labels:
      environment: "{{ environment }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: External NAT
        nat_ip: "{{ address_name }}"
        type: "{{ network_type }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    state: "{{ state }}"
