---
- name: Ensure our TCP ports are closed
  register: my_ports
  google.cloud.gcp_compute_firewall:
    name: open-tcp-ports
    network:
      selflink: "global/networks/{{ network }}"
    allowed:
    - ip_protocol: tcp
      ports: "{{ ports }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    state: "{{ state }}"

- name: Ensure we can't ping things
  register: my_ping
  google.cloud.gcp_compute_firewall:
    name: allow-icmp
    network:
      selflink: "global/networks/{{ network }}"
    allowed:
    - ip_protocol: icmp
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    state: "{{ state }}"

- name: print shit out
  ansible.builtin.debug:
    var: my_ports
